ESchoolRazor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ESchoolRazor.Services;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;

namespace ESchoolRazor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }

        public IActionResult OnGetSetLanguage(string lang, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(lang, lang)),
                new CookieOptions { IsEssential = true, Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );
            return LocalRedirect(returnUrl);
        }
    }
}

ESchoolRazor/Pages/Shared/_Layout.cshtml
@inject ESchoolRazor.SharedViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ESchoolRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ESchoolRazor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">@Localizer.GetLocalizedString("Home")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="Students/Index">@Localizer.GetLocalizedString("Students")</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">@Localizer.GetLocalizedString("Privacy")</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <partial name="_SelectLanguagePartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ESchoolRazor - <a asp-area="" asp-page="/Privacy">@Localizer.GetLocalizedString("Privacy")</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

ESchoolRazor/Pages/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options


@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@inject ESchoolRazor.SharedViewLocalizer Localizer

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
            .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
            .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" :
            $"~{Context.Request.Path.Value}{Context.Request.QueryString.Value}";
}
<ul class="navbar-nav">
    <li class="nav-item">
        @if (requestCulture.RequestCulture.UICulture.Name == "uk-UA")
        {
            <a class="nav-link text-dark" asp-page="/Index" asp-page-handler="SetLanguage" asp-route-lang="en-US"
                asp-route-returnUrl="@returnUrl">@Localizer.GetLocalizedString("Eng")</a>
        }
        else
        {
            <a class="nav-link text-dark" asp-page="/Index" asp-page-handler="SetLanguage" asp-route-lang="uk-UA"
                asp-route-returnUrl="@returnUrl">Ukr</a>
        }
    </li>
</ul>